sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t zhenyuan-Li/react-test -f ./client/Dockerfile.dev ./client
  # Other tests can be also build here
script:
  - docker run -e CI=true zhenyuan-Li/react-test npm test
after-success:
  - docker build -t Zhenyuan-Li/ffc-client ./client
  - docker build -t Zhenyuan-Li/ffc-nginx ./nginx
  - docker build -t Zhenyuan-Li/ffc-server ./server
  - docker build -t Zhenyuan-Li/ffc-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push Zhenyuan-Li/ffc-client
  - docker push Zhenyuan-Li/ffc-nginx
  - docker push Zhenyuan-Li/ffc-server
  - docker push Zhenyuan-Li/ffc-worker
