sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t zhenyuan0li/ffc-test -f ./client/Dockerfile.dev ./client
  # Other tests can be also build here
script:
  - docker run -e CI=true zhenyuan0li/ffc-test npm test
after-success:
  - docker build -t zhenyuan0li/ffc-client ./client
  - docker build -t zhenyuan0li/ffc-nginx ./nginx
  - docker build -t zhenyuan0li/ffc-server ./server
  - docker build -t zhenyuan0li/ffc-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push zhenyuan0li/ffc-client
  - docker push zhenyuan0li/ffc-nginx
  - docker push zhenyuan0li/ffc-server
  - docker push zhenyuan0li/ffc-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: ffc
  env: Ffc-env
  bucket_name: elasticbeanstalk-us-east-2-218664566765
  bucket_path: docker-ffc
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
